### ISSUE TITLE
Update the Initiate Use Agreement form based on the following requirement.

### ISSUE THREAD

**Issue by monixis** [monixis/useagreement#2]
Hi Monish,

I need to have the Use Agreement form updated.  Many of the researchers
that contact me are from outside of the U.S.  I would like the Researcher
Information section of the form to allow them to more easily add an
international address.  I'd like to make the following changes:

Date: (no change)

Researcher's Name: (no change)

Street Address:

City/State: (no change)

Zip code or Postal code:

Country:

Thanks,
John

**Comment by DeepDand** [comment]
Ok. Starting to work on it.

**Comment by DeepDand** [comment]
This is done. The form contains required fields and git has been updated as well.
